### ISSUE TITLE
sopor usb brailleback para android

### ISSUE THREAD

**Issue by discapacidad5** [cynthia/operavox#1]
Hi I would like to have a version of brailleback with support for lines alva by USB port could allude me Excuse my bad english use google translator

But with brailleback I can not take advantage of my old braille line that does not have bluetooth

I think this will help thousands of people who have old braille lines for how expensive it is to get a new one

Thanks for reading me sorry if the publication does not use it correctly but I do not sew how to write here

**Comment by cynthia** [comment]
In this case, Brailleback support relies on Android's platform support and this merely hooks into the platform's support. If the OS supports it (which I don't think it does) it should work just fine - as for that bit, please file a bug in Android's issue tracker.

Also, please do not cross post unless you haven't got a reply from one repository within a reasonable timeframe.
